/**
 * Custom Worker entry that wraps the OpenNext-generated `.open-next/worker.js`
 * with hostname canonicalization:
 *
 *   pollpotato.com/{app,p,auth}/*  → 308 → app.pollpotato.com/<same>
 *   app.pollpotato.com/            → 308 → pollpotato.com/
 *
 * Everything else passes through to the OpenNext handler unchanged. We do
 * this here instead of in next.config.ts because Next's `has: { type: "host" }`
 * matcher treats `value` as an unanchored regex — `pollpotato.com` also
 * matched `app.pollpotato.com` and produced a 308 loop. Worker-level Host
 * inspection is unambiguous.
 */

// .open-next/worker.js is generated by `opennextjs-cloudflare build` before
// wrangler bundles this entry. TypeScript can't see it; suppress per-import.
// @ts-expect-error - generated at build time
import openNextWorker from "../.open-next/worker.js";

// Durable Object classes ship from the OpenNext worker. Re-export so wrangler
// can bind them later without touching this file (none are wired today).
// @ts-expect-error - generated at build time
export { DOQueueHandler, DOShardedTagCache, BucketCachePurge } from "../.open-next/worker.js";

const MARKETING_HOST = "pollpotato.com";
const APP_HOST = "app.pollpotato.com";

// Paths that only make sense on the app subdomain. `/api/*` deliberately
// stays available on both hosts so SEO crawlers and embeds aren't blocked.
const APP_ONLY_PREFIXES = ["/app", "/p", "/auth"];

function canonicalRedirect(request: Request): Response | null {
  // Skip canonicalization on local dev (wrangler/workerd synthesizes the
  // first-routes hostname for every request, so without this guard /p/,
  // /app/, /auth/ routes redirect away from localhost). Cloudflare's edge
  // always attaches cf-ray, so its presence is a reliable production signal.
  if (!request.headers.get("cf-ray")) return null;

  const url = new URL(request.url);
  const host = url.host.toLowerCase();
  const path = url.pathname;

  if (host === MARKETING_HOST) {
    const isAppPath = APP_ONLY_PREFIXES.some(
      (prefix) => path === prefix || path.startsWith(prefix + "/"),
    );
    if (isAppPath) {
      url.host = APP_HOST;
      return Response.redirect(url.toString(), 308);
    }
  }

  if (host === APP_HOST && path === "/") {
    url.host = MARKETING_HOST;
    return Response.redirect(url.toString(), 308);
  }

  return null;
}

const handler = {
  async fetch(
    request: Request,
    env: unknown,
    ctx: unknown,
  ): Promise<Response> {
    const redirect = canonicalRedirect(request);
    if (redirect) return redirect;
    return openNextWorker.fetch(request, env, ctx);
  },
};

export default handler;
