/**
 * Custom Worker entry that wraps the OpenNext-generated `.open-next/worker.js`
 * with hostname canonicalization:
 *
 *   pollpotato.com/{app,p,auth}/*  → 308 → app.pollpotato.com/<same>
 *   app.pollpotato.com/            → 308 → pollpotato.com/
 *
 * Everything else passes through to the OpenNext handler unchanged. We do
 * this here instead of in next.config.ts because Next's `has: { type: "host" }`
 * matcher treats `value` as an unanchored regex — `pollpotato.com` also
 * matched `app.pollpotato.com` and produced a 308 loop. Worker-level Host
 * inspection is unambiguous.
 */

// .open-next/worker.js is generated by `opennextjs-cloudflare build` before
// wrangler bundles this entry. TypeScript can't see it; suppress per-import.
// @ts-expect-error - generated at build time
import openNextWorker from "../.open-next/worker.js";

// Durable Object classes ship from the OpenNext worker. Re-export so wrangler
// can bind them later without touching this file (none are wired today).
// @ts-expect-error - generated at build time
export { DOQueueHandler, DOShardedTagCache, BucketCachePurge } from "../.open-next/worker.js";

const MARKETING_HOST = "pollpotato.com";
const APP_HOST = "app.pollpotato.com";
const WWW_HOST = "www.pollpotato.com";

// Paths that only make sense on the app subdomain. `/api/*` deliberately
// stays available on both hosts so SEO crawlers and embeds aren't blocked.
const APP_ONLY_PREFIXES = ["/app", "/p", "/auth"];

function isAppOnlyPath(path: string): boolean {
  return APP_ONLY_PREFIXES.some(
    (prefix) => path === prefix || path.startsWith(prefix + "/"),
  );
}

function canonicalRedirect(request: Request): Response | null {
  // Skip canonicalization on local dev (wrangler/workerd synthesizes the
  // first-routes hostname for every request, so without this guard /p/,
  // /app/, /auth/ routes redirect away from localhost). Cloudflare's edge
  // always attaches cf-ray, so its presence is a reliable production signal.
  if (!request.headers.get("cf-ray")) return null;

  // Only canonicalize top-level GET navigations. POST/PUT/PATCH/DELETE are
  // either server actions (Next.js posts to the current page URL), API
  // calls, or sign-in form submissions — they aren't user-visible URL
  // changes, so redirecting them would just break the CORS preflight and
  // kill the request. Both hosts run the same Worker, so the handler
  // executes correctly wherever it lands.
  if (request.method !== "GET" && request.method !== "HEAD") return null;

  // Don't 308 Next.js RSC prefetch fetches across hostnames — the browser
  // would block them via CORS because the requesting origin (pollpotato.com)
  // differs from the redirect target (app.pollpotato.com). Both hosts run
  // the same Worker so the payload is identical either way. The user's
  // eventual click is a top-level navigation and DOES get canonicalized.
  const url = new URL(request.url);
  if (
    request.headers.get("RSC") === "1" ||
    request.headers.get("Next-Router-Prefetch") === "1" ||
    url.searchParams.has("_rsc")
  ) {
    return null;
  }
  const host = url.host.toLowerCase();
  const path = url.pathname;

  // A logged-in visitor hitting the site root wants their polls, not the
  // marketing pitch (and the pitch shows a confusing "Sign in" to them, since
  // the marketing header is statically cached and never checks the session).
  // Bounce them to the app. This is a TEMPORARY (302) redirect, deliberately
  // NOT the permanent 308 used for host canonicalization: it's conditional on
  // auth state, so caching it would strand the user on /app after they sign
  // out. Anonymous visitors (and crawlers) have no session cookie, fall
  // through, and get the cached marketing page — so SEO is untouched.
  const KNOWN_HOSTS = [MARKETING_HOST, WWW_HOST, APP_HOST];
  if (path === "/" && KNOWN_HOSTS.includes(host) && hasSession(request)) {
    url.host = APP_HOST;
    url.pathname = "/app";
    return redirectTemporary(url.toString());
  }

  // www.pollpotato.com is not a canonical host. Route straight to the right
  // bare-domain host based on path so the user only sees one 308, not two.
  if (host === WWW_HOST) {
    url.host = isAppOnlyPath(path) ? APP_HOST : MARKETING_HOST;
    return redirect308(url.toString());
  }

  if (host === MARKETING_HOST) {
    if (isAppOnlyPath(path)) {
      url.host = APP_HOST;
      return redirect308(url.toString());
    }
  }

  if (host === APP_HOST && path === "/") {
    url.host = MARKETING_HOST;
    return redirect308(url.toString());
  }

  return null;
}

/**
 * 308 with `Cache-Control: no-store` so browsers don't aggressively cache
 * the redirect. Without this, a redirect emitted while our route rules
 * were less-than-perfect (early M9-G iterations) could stick in users'
 * caches for days even after we deployed the fix, because 308 is
 * "permanent" and Chromium treats it accordingly.
 */
function redirect308(location: string): Response {
  return new Response(null, {
    status: 308,
    headers: {
      Location: location,
      "Cache-Control": "no-store",
    },
  });
}

/** 302 (temporary) + no-store, for redirects that depend on request state. */
function redirectTemporary(location: string): Response {
  return new Response(null, {
    status: 302,
    headers: {
      Location: location,
      "Cache-Control": "no-store",
    },
  });
}

/**
 * True when the request carries a Neon Auth session cookie. Neon Auth (Better
 * Auth under the hood) names the session cookie `__Secure-neon-auth.session_token`
 * — we substring-match `neon-auth.session_token` so we also catch its chunked
 * `.0`/`.1` variants, without matching the transient OAuth
 * `...session_challange` or the `...local.session_data` cookies. This is a
 * presence check only: an expired cookie still redirects to /app, where the
 * app layout does the real session lookup and renders the signed-out view.
 * That edge is accepted in exchange for keeping this a zero-cost edge check.
 */
function hasSession(request: Request): boolean {
  const cookie = request.headers.get("Cookie");
  return !!cookie && cookie.includes("neon-auth.session_token");
}

// Host-specific robots.txt for the app subdomain. Next's robots.ts is
// host-agnostic and serves the same body on both hosts, so without this
// override app.pollpotato.com/robots.txt advertises `Allow: /` — exactly
// the opposite of what we want for the non-canonical host. Intercept here
// instead of plumbing host-awareness into the Next route.
const APP_ROBOTS_BODY = "User-agent: *\nDisallow: /\n";

function appHostRobots(request: Request): Response | null {
  const url = new URL(request.url);
  if (url.host.toLowerCase() !== APP_HOST) return null;
  if (url.pathname !== "/robots.txt") return null;
  return new Response(APP_ROBOTS_BODY, {
    headers: { "Content-Type": "text/plain; charset=utf-8" },
  });
}

// Stamp every app-subdomain response with X-Robots-Tag: noindex so a backlink
// to e.g. app.pollpotato.com/p/<slug> can never produce an index entry, even
// if robots.txt is ignored. Marketing/SEO lives exclusively on the bare host.
function withAppHostNoIndex(host: string, response: Response): Response {
  if (host !== APP_HOST) return response;
  const headers = new Headers(response.headers);
  headers.set("X-Robots-Tag", "noindex, nofollow");
  return new Response(response.body, {
    status: response.status,
    statusText: response.statusText,
    headers,
  });
}

const handler = {
  async fetch(
    request: Request,
    env: unknown,
    ctx: unknown,
  ): Promise<Response> {
    const redirect = canonicalRedirect(request);
    if (redirect) return redirect;

    const robots = appHostRobots(request);
    if (robots) return robots;

    const host = new URL(request.url).host.toLowerCase();
    const response = await openNextWorker.fetch(request, env, ctx);
    return withAppHostNoIndex(host, response);
  },
};

export default handler;
